/**
 * Mock email data for development and demo fallback.
 * Realistic emails that showcase all 5 streams.
 */

const now = new Date()
const hoursAgo = (h) => new Date(now.getTime() - h * 60 * 60 * 1000)
const daysAgo = (d) => new Date(now.getTime() - d * 24 * 60 * 60 * 1000)

export const MOCK_EMAILS = [
  // ── People ──
  {
    id: 'mock-1',
    threadId: 't-1',
    from: 'Aradhy Shukla <aradhy@gmail.com>',
    senderName: 'Aradhy Shukla',
    senderEmail: 'aradhy@gmail.com',
    to: 'you@gmail.com',
    subject: 'Hackathon project update — ZwoopMail is looking sick 🔥',
    date: hoursAgo(1),
    snippet: 'Hey! Just pushed the latest changes to the repo. The Caldera design system looks incredible. Can you review the sidebar component when you get a chance?',
    bodyText: 'Hey!\n\nJust pushed the latest changes to the repo. The Caldera design system looks incredible with the ASCII elements.\n\nCan you review the sidebar component when you get a chance? I think we need to tweak the stream colors a bit.\n\nAlso, have you set up the Google Cloud project for OAuth yet? We need the client ID before we can test the Gmail integration.\n\nLet\'s crush this! 🚀\n\n— Aradhy',
    bodyHtml: '',
    isUnread: true,
    isStarred: true,
    labels: ['INBOX', 'UNREAD', 'STARRED'],
    category: 'people',
  },
  {
    id: 'mock-2',
    threadId: 't-2',
    from: 'Priya Sharma <priya.sharma@outlook.com>',
    senderName: 'Priya Sharma',
    senderEmail: 'priya.sharma@outlook.com',
    to: 'you@gmail.com',
    subject: 'Re: Weekend plans?',
    date: hoursAgo(4),
    snippet: 'Saturday works for me! Let\'s meet at the café near Connaught Place around 3pm. I\'ll bring the board games.',
    bodyText: 'Saturday works for me! Let\'s meet at the café near Connaught Place around 3pm. I\'ll bring the board games.\n\nSee you there! 🎲',
    bodyHtml: '',
    isUnread: true,
    isStarred: false,
    labels: ['INBOX', 'UNREAD'],
    category: 'people',
  },
  {
    id: 'mock-3',
    threadId: 't-3',
    from: 'Prof. Mehta <r.mehta@university.edu>',
    senderName: 'Prof. Mehta',
    senderEmail: 'r.mehta@university.edu',
    to: 'you@gmail.com',
    subject: 'Assignment deadline extended to Friday',
    date: daysAgo(1),
    snippet: 'Dear students, Due to the server issues last night, I am extending the deadline for Assignment 3 to this Friday 11:59 PM.',
    bodyText: 'Dear students,\n\nDue to the server issues last night, I am extending the deadline for Assignment 3 to this Friday 11:59 PM IST.\n\nPlease submit your work on the course portal. Late submissions will not be accepted.\n\nBest regards,\nProf. R. Mehta',
    bodyHtml: '',
    isUnread: false,
    isStarred: false,
    labels: ['INBOX'],
    category: 'people',
  },

  // ── Transactions ──
  {
    id: 'mock-4',
    threadId: 't-4',
    from: 'HyugaLife <noreply@hyugalife.com>',
    senderName: 'HyugaLife',
    senderEmail: 'noreply@hyugalife.com',
    to: 'you@gmail.com',
    subject: 'Your order #1002738275 is out for delivery! 🚚',
    date: hoursAgo(2),
    snippet: 'Your order is out for delivery today! Track your package for live updates. Estimated delivery: Today by 8 PM.',
    bodyText: 'Hi there!\n\nGreat news — your order #1002738275 is out for delivery!\n\nEstimated delivery: Today by 8 PM\nItems: NAKPRO Impact Whey Protein 1kg\n\nTrack your package: https://hyugalife.com/track/1002738275\n\nThanks for shopping with HyugaLife! 💪',
    bodyHtml: '',
    isUnread: true,
    isStarred: false,
    labels: ['INBOX', 'UNREAD'],
    category: 'transactions',
  },
  {
    id: 'mock-5',
    threadId: 't-5',
    from: 'Amazon <ship-confirm@amazon.in>',
    senderName: 'Amazon',
    senderEmail: 'ship-confirm@amazon.in',
    to: 'you@gmail.com',
    subject: 'Your Amazon order has shipped!',
    date: daysAgo(1),
    snippet: 'Your order containing "Logitech G502 Gaming Mouse" has been shipped and will arrive by Jul 29.',
    bodyText: 'Your order has been shipped!\n\nOrder #402-1234567-8901234\nItem: Logitech G502 HERO Gaming Mouse\nEstimated delivery: Jul 29, 2026\n\nTrack your package on Amazon.',
    bodyHtml: '',
    isUnread: false,
    isStarred: false,
    labels: ['INBOX'],
    category: 'transactions',
  },
  {
    id: 'mock-6',
    threadId: 't-6',
    from: 'HDFC Bank <alerts@hdfcbank.net>',
    senderName: 'HDFC Bank',
    senderEmail: 'alerts@hdfcbank.net',
    to: 'you@gmail.com',
    subject: 'Transaction Alert: INR 2,499 debited from your account',
    date: hoursAgo(6),
    snippet: 'Dear Customer, INR 2,499.00 has been debited from your HDFC Bank account ending 4521 on 27-Jul-2026. Available balance: INR 15,230.50',
    bodyText: 'Dear Customer,\n\nINR 2,499.00 has been debited from your HDFC Bank account ending 4521 on 27-Jul-2026.\n\nTransaction details:\nAmount: INR 2,499.00\nMerchant: SWIGGY\nDate: 27-Jul-2026 10:34 AM\nAvailable balance: INR 15,230.50\n\nIf this was not done by you, call 1800-202-6161 immediately.',
    bodyHtml: '',
    isUnread: true,
    isStarred: false,
    labels: ['INBOX', 'UNREAD'],
    category: 'transactions',
  },

  // ── Newsletters ──
  {
    id: 'mock-7',
    threadId: 't-7',
    from: 'Bytes <hello@bytes.dev>',
    senderName: 'Bytes',
    senderEmail: 'hello@bytes.dev',
    to: 'you@gmail.com',
    subject: '🗞️ React 20 just dropped, and it\'s wild',
    date: hoursAgo(8),
    snippet: 'React 20 brings server components by default, a new compiler, and says goodbye to useEffect. Here\'s everything you need to know...',
    bodyText: 'React 20 just dropped!\n\nKey changes:\n• Server components are now the default\n• New React Compiler eliminates the need for useMemo/useCallback\n• useEffect is officially deprecated\n• New use() hook for async data\n\nRead the full breakdown: https://bytes.dev/react-20',
    bodyHtml: '',
    isUnread: true,
    isStarred: false,
    labels: ['INBOX', 'UNREAD'],
    category: 'newsletters',
  },
  {
    id: 'mock-8',
    threadId: 't-8',
    from: 'Morning Brew <crew@morningbrew.com>',
    senderName: 'Morning Brew',
    senderEmail: 'crew@morningbrew.com',
    to: 'you@gmail.com',
    subject: 'Daily Brew ☕ — India\'s startup funding hits $12B in H1 2026',
    date: daysAgo(1),
    snippet: 'Good morning! India\'s startup ecosystem raised $12 billion in the first half of 2026, marking a 40% increase from the same period last year...',
    bodyText: 'Good morning!\n\n☕ India\'s startup ecosystem raised $12 billion in the first half of 2026, marking a 40% increase YoY.\n\n📱 Apple announced the iPhone 17 Ultra with a new AI chip.\n\n🤖 OpenAI released GPT-5 Turbo for enterprise customers.\n\nRead more: morningbrew.com',
    bodyHtml: '',
    isUnread: false,
    isStarred: false,
    labels: ['INBOX'],
    category: 'newsletters',
  },

  // ── Notifications ──
  {
    id: 'mock-9',
    threadId: 't-9',
    from: 'LinkedIn <notifications@linkedin.com>',
    senderName: 'LinkedIn',
    senderEmail: 'notifications@linkedin.com',
    to: 'you@gmail.com',
    subject: 'Tech Intern — React Native / NestJS at ADSMUNCH PRIVATE LIMITED',
    date: hoursAgo(3),
    snippet: 'SkillNexGen Technical Content Writing Intern: Internship Opportunity: Technical Content Writing. Your job alert for Tech Intern...',
    bodyText: 'New job alert!\n\nTech Intern — React Native / NestJS\nADSMUNCH PRIVATE LIMITED\nLocation: Delhi, India\nType: Internship\n\nView jobs picked for you based on your profile.',
    bodyHtml: '',
    isUnread: true,
    isStarred: false,
    labels: ['INBOX', 'UNREAD'],
    category: 'notifications',
  },
  {
    id: 'mock-10',
    threadId: 't-10',
    from: 'GitHub <noreply@github.com>',
    senderName: 'GitHub',
    senderEmail: 'noreply@github.com',
    to: 'you@gmail.com',
    subject: '[EVERYDAY-ARADHY/ZwoopMail] Pull request #3: Add sidebar component',
    date: hoursAgo(5),
    snippet: 'EVERYDAY-ARADHY opened a pull request: Add sidebar component with stream navigation, theme toggle, and ASCII-styled dividers.',
    bodyText: 'EVERYDAY-ARADHY opened a pull request in ZwoopMail:\n\n#3 Add sidebar component\n\nChanges:\n- Added Sidebar.jsx with stream navigation\n- Added Sidebar.css with Caldera tokens\n- Added theme toggle\n- Added ASCII-styled section dividers\n\nReview requested.',
    bodyHtml: '',
    isUnread: false,
    isStarred: false,
    labels: ['INBOX'],
    category: 'notifications',
  },
  {
    id: 'mock-11',
    threadId: 't-11',
    from: 'Supabase <ant.wilson@supabase.com>',
    senderName: 'Supabase',
    senderEmail: 'ant.wilson@supabase.com',
    to: 'you@gmail.com',
    subject: 'Your Supabase Project EVERYDAY-ARADHY\'s has been paused',
    date: daysAgo(1),
    snippet: 'Hi there, To optimize cloud resources, we automatically pause free-tier projects after 7 days of inactivity.',
    bodyText: 'Hi there,\n\nTo optimize cloud resources, we automatically pause free-tier projects after 7 days of inactivity.\n\nYour project EVERYDAY-ARADHY\'s Project has been paused.\n\nTo resume, visit your dashboard: https://supabase.com/dashboard',
    bodyHtml: '',
    isUnread: false,
    isStarred: false,
    labels: ['INBOX'],
    category: 'notifications',
  },

  // ── Promotions ──
  {
    id: 'mock-12',
    threadId: 't-12',
    from: 'Unloqit <noreply@unloqit.co>',
    senderName: 'Unloqit',
    senderEmail: 'noreply@unloqit.co',
    to: 'you@gmail.com',
    subject: 'Expiring Tomorrow: Your gift vouchers worth ₹400!',
    date: daysAgo(1),
    snippet: '1 gift vouchers from The Man Company and others waiting for you. You\'ve unlocked ₹400 in gifts collected at HyugaLife...',
    bodyText: '⚡ Expiring Tomorrow!\n\nYou have 1 gift voucher waiting:\n• The Man Company — ₹400 off\n\nRedeem before midnight tomorrow.\n\nShop now: https://unloqit.co/redeem',
    bodyHtml: '',
    isUnread: true,
    isStarred: false,
    labels: ['INBOX', 'UNREAD'],
    category: 'promotions',
  },
  {
    id: 'mock-13',
    threadId: 't-13',
    from: 'Zomato <noreply@zomato.com>',
    senderName: 'Zomato',
    senderEmail: 'noreply@zomato.com',
    to: 'you@gmail.com',
    subject: 'Flat 60% OFF on your next order 🍕',
    date: daysAgo(2),
    snippet: 'We miss you! Use code COMEBACK60 for flat 60% off (up to ₹150) on your next Zomato order. Valid till Sunday.',
    bodyText: 'We miss you! 🍕\n\nUse code: COMEBACK60\nFlat 60% OFF (up to ₹150)\nValid till Sunday\n\nOrder now on Zomato!',
    bodyHtml: '',
    isUnread: false,
    isStarred: false,
    labels: ['INBOX'],
    category: 'promotions',
  },
  {
    id: 'mock-14',
    threadId: 't-14',
    from: 'MyBharat <noreply@mybharat.gov.in>',
    senderName: 'MyBharat',
    senderEmail: 'noreply@mybharat.gov.in',
    to: 'you@gmail.com',
    subject: 'Participate in the Nasha Mukt Yuva for Viksit Bharat cultural activities',
    date: daysAgo(2),
    snippet: 'Dear Participant, Us... Participate in the Nasha Mukt Yuva for Viksit Bharat cultural activities on MY Bharat portal.',
    bodyText: 'Dear Participant,\n\nYou are invited to participate in the Nasha Mukt Yuva for Viksit Bharat cultural activities on the MY Bharat portal.\n\nRegister at: https://mybharat.gov.in',
    bodyHtml: '',
    isUnread: false,
    isStarred: false,
    labels: ['INBOX'],
    category: 'promotions',
  },
]

/**
 * Group mock emails by category/stream
 */
export function categorizeMockEmails() {
  const categorized = {
    people: [],
    transactions: [],
    newsletters: [],
    notifications: [],
    promotions: [],
  }

  MOCK_EMAILS.forEach((email) => {
    if (categorized[email.category]) {
      categorized[email.category].push(email)
    }
  })

  return categorized
}
